OlympusDAO-Education/Documentation

SUMMARY.md
glossary.md

I just want to get the ball rolling so that we get used to iterate over the docs content. Here I thought it would be cool to start adding a glossary since a lot of people get confused about abbreviations and their terminology.

add glossary with first entries

---

README.md

Update some information on the Introduction page, like how stakers and bonders can participate and benefit from Olympus.

Update the Introduction Page

---

glossary.md

Adding PCV, RFV and SLP to the mix. Let me know what you think and if you would like something to be rewritten.

add more abbreviations to glossary

---

equations.md

I am trying to elaborate more on the staking equations here so that it is more easily digestible.

elaborate more on staking equations

---

bonds.md

See if there are things worth merging

Bonds edit

---

glossary.md

Adding a couple of juicy abbreviations here. Please check if the descriptions are correct. I reckon one or the other might better be rewritten. ❤️

extend glossary

---

faqs/basics.md

Ported some questions from ELI5 doc to kickstart the FAQ page

Add a new FAQ section

---

SUMMARY.md

Update table of content to include FAQ section

Update table of content

---

architecture.md

Minimal change to start on the architecture structure.

create architecture sections

---

SUMMARY.md
contracts.md

As discussed in Discord, this is just the outline to get started. If the contract addresses are complete let's get this merged and then we can provide separate PRs to provide more context and in detail descriptions.

add new page for contracts docs

---

using-the-website/staking.md

Update the definition for some terms

Update staking instruction page

---

faqs/basics.md

Two new entries have been ported from the ELI5 doc

Add more entries to FAQ

---

faqs/basics.md

Add a new FAQ entry

---

faqs/basics.md

Rewrite the mathematical formulae based on TeX system

Fix equation display on GitBook

---

README.md
SUMMARY.md
links.md

As discussed in Discord we wanted to give all internal and external links their own space.

add separate links section to references

---

audits.md

Adding the second audit report. Though this one is not so cool to link because most links to files are kind of broken. That does not foster confidence and transparency. I hope that we can fix this or make it better in the future.

add second audit report

---

SUMMARY.md
using-the-website/staking_lp.md

Add instruction for staking LP tokens

Add instruction for staking LP tokens

---

SUMMARY.md

As discussed in our session earlier let's try something like this. Let me know if the wording works for you.

add section for protocol internals

---

SUMMARY.md
contribute.md

Just spitballing here. This section will show potential ohmies how to get involved in OlympusDAO. I intend the contribute page to be a guide on how to contribute to this GitBook documentation.

Add "Get Involved" section

---

using-the-website/staking.md

Indent the images in the ordered list to preserve the list continuity

Fix the issue where the embedded images break the ordered list

---

contribute.md

Add high-level workflow for updating the documentation and also instructions for cloning the repo

Add basic workflow

---

contribute.md

Show the steps on how to create a branch and push it to the repository

Add instructions to create a branch

---

staking.md

Update the staking page to mention sOHM is transferable and composable with other DeFi protocols

sOHM is transferable now

---

contracts.md

After the latest contributions the format got a bit out of sync. Trying to align the docs in this file to have a coherent experience.

make versioned contract list consistent

---

faqs/basics.md

1. Use the term "reward yield" in place of "rebase rate"
2. Use reward rate in APY calculation instead of a fixed number since it is subject to change

Update the FAQ section

---

staking.md

1. Rebase rewards come from bond proceeds
2. Rephrase how staking for long term could benefit the stakers

Update the staking page

---

equations.md

1. Fix bond price equation
2. Remove the mention of sales mechanism
3. Mention about OHM buy back

Update Equation page

---

SUMMARY.md
using-etherscan/staking.md
using-etherscan/unstaking.md

Several users have issues using Olympus website due to hosting problems. So a guide is made to show them how to stake/unstake via Etherscan.

Add instructions to stake/unstake via Etherscan

---

SUMMARY.md
using-the-website/bond_weth.md

Also update the layout for "Purchase A Bond (1, 1)" section. I plan to separate the instructions for different bond types into their own separate section.

Add wETH bond instruction

---

initial-network-state.md

- BCV is an adjustable value
- Correct the bond vesting term
- How OHM is distributed when someone purchases a bond

Update the initial policy states

---

equations.md

Continued from #91 
- Add OHM Supply section
- Add Backing per OHM section
- Remove the Treasury section

Restructure the Equation page

---

SUMMARY.md
contracts/allocators.md

Also add a general Allocators section

Add AAVE allocator contract

---

contracts/dao.md
contracts/treasury.md

Due to this, the treasury now has a different setup from the DAO contract

Update the multisig setup for the DAO contract

---

basics/basics.md

Also added a link to the Dune query which shows the RFV growth

Update the bank-run FAQ based on the latest protocol metrics

---

basics/basics.md

Somebody on Twitter pointed out some confusion they had based on our documentation. 
https://twitter.com/crypto_sammy/status/1440975450826842113

remove stablecoin terminology when describing OHM

---

basics/basics.md

https://www.merriam-webster.com/dictionary/beneficiary
https://www.merriam-webster.com/dictionary/beneficial

change "beneficiary" to "beneficial"

---

basics/bonding.md

Make it easier to understand for users

Update bonding definition

---

contracts/bonds.md

Adding LUSD and OHM / LUSD bonds to our docs. Also moving the sections around to make it alphabetical again.

add LUSD bonds to contract docs

---

references/translations.md

Due to GitBook subscription issue, we didn't publish it as part of the language variants. So this is a temporary solution

Add a link to Turkish translation

---

basics/basics.md

Use a more realistic APY figure based on the current reward rate framework. Also talk about runway briefly

Update the FAQ re: high staking APY

---

using-the-website/bonds/bond_cvx.md

bond_cvx.md

---

using-the-website/bonds/bond_ohm-weth.md

Bonding instructions for ohm-weth

bond_ohm-weth.md

---

basics/migration.md

Also avoid the usage of the word "spend"

Emphasize the need to approve each v1 token

---

basics/migration.md

Also add an entry about how gOHM still earns you rebase rewards

Add the TLDR of the migration

---

SUMMARY.md
basics/migration.md

Update the V2 migration FAQ

---

contracts/tokens.md

Expound on gOHM

---

contracts/policy.md

Update the Policy multi-sig

---

contracts/bonds.md

Also remove duplicated sentences

Add CVX bond contract

---

basics/migration.md

Also emphasize that existing users can sit tight and not lose out any rebase rewards if they don't migrate

Remove the mention of the two-month migration period

---

contracts/allocators.md

Let me know what you would maybe like to see in terms of additional explanations about the newer versions.

add convex allocator versions

---

contracts/staking.md

The multiple contract updates are associated with V1.1 and V2 migrations

Added the new staking contract

---

contracts/dao.md
contracts/treasury.md

DAO owners have been updated: https://gnosis-safe.io/app/eth:0x245cc372C84B3645Bf0Ffe6538620B04a217988B/settings/owners

Update treasury contract and signer information
